apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-redirect-backend
  labels:
    app: www-redirect-backend
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: www-redirect-backend
  template:
    metadata:
      labels:
        app: www-redirect-backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - www-redirect-backend
            topologyKey: kubernetes.io/hostname
      containers:
      - name: www-redirect-backend
        image: acoshift/www-redirect-backend:1.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: www-redirect-backend
  labels:
    app: www-redirect-backend
spec:
  selector:
    app: www-redirect-backend
  ports:
  - name: http
    port: 8080
